### ISSUE TITLE
Usable Quest Item management

### ISSUE THREAD

**Issue by blockspiders** [Slackwise/SlackUI#13]
Add a keybindable slot in the UI with a selection for all (only relevant/usable in the area?) usable Quest Items in inventory, especially where they already aren't usable with the Special Action button.
![questitems](https://user-images.githubusercontent.com/6454508/99732483-30a3f300-2a85-11eb-8f40-8ac6355d3c3d.png)

**Comment by Slackwise** [comment]
Is the idea that this UI element swaps what this keybinding does?

We have to keep in mind that combat locks keybinding and macros so you can't make "smart" keybindings for combat.

**Comment by Slackwise** [comment]
Okay so OPie is an add-on that does radial menus for casting and stuff so looking into that as a UI or at least how it creates dynamic action buttons.

**Comment by Slackwise** [comment]
Okay, so as we discussed, using those "flyout" (dropdown) menus similar to this addon would be a good choice:

https://www.curseforge.com/wow/addons/flyoutbutton-custom

https://www.curseforge.com/wow/addons/floflyout

**Comment by Slackwise** [comment]
This is no longer relevant as the new UI as of Dragonflight lets you just right-click to use the relevant quest item.

**Comment by Slackwise** [comment]
This is no longer relevant as the new UI as of Dragonflight lets you just right-click to use the relevant quest item.
